### ISSUE TITLE
有没有国际版OD能用的？

### ISSUE THREAD

**Issue by ymh1147** [beetcb/sosf#1]
刚才试了下Vercel获取OD国际版，输入重定向地址就提示TypeError: Only absolute URLs are supported

**Comment by beetcb** [comment]
有的。在配置环境变量那一步，运行 CLI 工具后，可选国际版或世纪互联版本

![3](https://user-images.githubusercontent.com/63141491/107870934-12a92b80-6ed8-11eb-8007-523f8d954cb0.png)

**Comment by ymh1147** [comment]
vercel部署好了，使用分配域名可以看到Plz specify the param. For example: https://your.app/?path=/demo.svg，但使用https://分配域名/?path=/demo.svg或者https://分配域名/?path=/path/to/file.md，则提示网关错误：
`502: BAD_GATEWAY
Code: NO_RESPONSE_FROM_FUNCTION
ID: hkg1::nrnx5-1613359117712-c45eb64800c9`

**Comment by beetcb** [comment]
这种报错不准确，提供一下 vercel 的控制台日志 @ymh1147

**Comment by ymh1147** [comment]
2021-02-15T03:18:37.522Z	03a480d7-0fc2-401e-945f-5cfc3aef7305	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'slice' of undefined","reason":{"errorType":"TypeError","errorMessage":"Cannot read property 'slice' of undefined","stack":["TypeError: Cannot read property 'slice' of undefined","    at db (/var/task/sosf/api/api.js:45:39)","    at exports.getToken (/var/task/sosf/api/api.js:86:21)","    at handler (/var/task/sosf/api/index.js:24:32)","    at Server.<anonymous> (/var/task/___vc_helpers.js:813:19)","    at Server.emit (events.js:315:20)","    at parserOnIncoming (_http_server.js:874:12)","    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'slice' of undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}
Unknown application error occurred

**Comment by beetcb** [comment]
你没有配置这三个吧！

![Screenshot_20210215-120735](https://user-images.githubusercontent.com/63141491/107904396-a33e4500-6f86-11eb-8f07-141c1247b20c.jpg)

报错是因为 AppId 没为空

**Comment by ymh1147** [comment]
![微信截图_20210215121548](https://user-images.githubusercontent.com/61814958/107904771-b1d92c00-6f87-11eb-9444-aae74256c7c2.png)

**Comment by beetcb** [comment]
是在本地项目根目录，你仔细看文档，这一步做完了才安装 vercel cli，所以自然是在本地的 `.env` 文件

**Comment by beetcb** [comment]
我看到你的邮件了，问题是你的根目录是 `sosf`，而不是本项目的那些文件

**Comment by beetcb** [comment]
![image](https://user-images.githubusercontent.com/63141491/107907866-bc97bf00-6f8f-11eb-80e2-96a88fd1597e.png)

像这样，在 sosf 文件夹内部署，.env 文件也要在这个文件夹里面

**Comment by ymh1147** [comment]
要崩溃了，我全部重做了一次，现在是
![2](https://user-images.githubusercontent.com/61814958/107911429-8cecb500-6f97-11eb-8470-39989276617a.png)
可打开“?path=/”又显示‘’Resource not found‘’，日志里面是
![1](https://user-images.githubusercontent.com/61814958/107911595-de953f80-6f97-11eb-92d0-6adbe4264b44.png)

**Comment by beetcb** [comment]
@ymh1147  好像已经成功了，`?path=/` 后面要接你网盘的文件的真实目录，而不是我提供的那个示例

**Comment by ymh1147** [comment]
额,好吧，真成功了，谢谢大佬指点

**Comment by beetcb** [comment]
我发现我没有给用户提供`部署目录`的自定义，现在默认部署了根目录，有时间我会改一下

**Comment by ymh1147** [comment]
一个很致命的问题，中文路径直接502，哪怕你是用的转义字符，这个需要想办法改一下
![微信截图_20210215151351](https://user-images.githubusercontent.com/61814958/107916044-89a9f700-6fa0-11eb-81ee-8c52c099e5a2.png)

**Comment by beetcb** [comment]
修复了，你本地已经配置好了，只需要更新下代码部署一次就 OK 了。还可以在 `.env` 里面新增 `base_dir` 来自定义部署文件夹 @ymh1147
